---
- src: https://github.com/lagoon-platform/ansible-role-configuration.git
  version: origin/master
  name: lagoon.configuration

- src: https://github.com/lagoon-platform/ansible-role-install.git
  version: origin/master
  name: lagoon.ansible_install

- src: https://github.com/lagoon-platform/ansible-role-docker.git
  version: origin/master
  name: lagoon.docker

- src: https://github.com/lagoon-platform/ansible-role-filesystem.git
  version: origin/master
  name: lagoon.filesystem
